version: "3"

tasks:
  format:
    desc: Run format with ruff
    cmds:
      - uv run ruff format app/

  check:
    desc: Run check with mypy
    cmds:
      - uv run mypy app/

  lint:
    desc: Run lint with ruff
    cmds:
      - uv run ruff check app/

  test:
    desc: Run pytest
    env:
      DATABASE_URL: postgresql+psycopg2://laborman:laborman@localhost:5432/laborman
    cmds:
      - uv run pytest .

  run:
    desc: Run the app
    cmds:
      - uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload