PRESETS = [
    {
        "id": "fastapi-react",
        "name": "FastAPI + React",
        "description": "Python API and React SPA.",
        "answers": {
            "project_kind": "Web",
            "languages": ["Python", "TypeScript"],
            "frameworks": ["FastAPI", "React"],
            "ai_tools": ["Claude", "Codex", "Cursor"],
            "test_strategy": ["pytest", "vitest"],
            "lint_format": ["ruff", "mypy", "eslint", "prettier"],
            "review_policy": "厳格",
        },
    },
    {
        "id": "go/echo-react",
        "name": "Go/Echo + React",
        "description": "Go API and React SPA.",
        "answers": {
            "project_kind": "Web",
            "languages": ["Go", "TypeScript"],
            "frameworks": ["Echo", "React"],
            "ai_tools": ["Claude", "Codex", "Cursor"],
            "test_strategy": ["testing", "vitest"],
            "lint_format": ["gofmt", "golangci-lint", "eslint", "prettier"],
            "review_policy": "厳格",
        },
    },
    {
        "id": "nextjs",
        "name": "Next.js",
        "description": "Single-framework web application preset.",
        "answers": {
            "project_kind": "Web",
            "languages": ["TypeScript"],
            "frameworks": ["Next.js"],
            "ai_tools": ["Claude", "Codex"],
            "test_strategy": ["vitest"],
            "lint_format": ["eslint", "prettier"],
            "review_policy": "柔軟",
        },
    },
    {
        "id": "python-api",
        "name": "Python API",
        "description": "Backend-only API service preset.",
        "answers": {
            "project_kind": "API",
            "languages": ["Python"],
            "frameworks": ["FastAPI"],
            "ai_tools": ["Claude", "Codex"],
            "test_strategy": ["pytest"],
            "lint_format": ["ruff", "mypy"],
            "review_policy": "厳格",
        },
    },
    {
        "id": "go-grpc",
        "name": "Go gRPC",
        "description": "Go gRPC service preset.",
        "answers": {
            "project_kind": "API",
            "languages": ["Go"],
            "frameworks": ["Buf"],
            "ai_tools": ["Claude", "Codex", "Cursor"],
            "test_strategy": ["testing"],
            "lint_format": ["gofmt", "golangci-lint"],
            "review_policy": "厳格",
        },
    },
]
